export const ERROR_CODE = {
    VALIDATION_ERROR        :'VALIDATION_ERROR',
    AUTHENTICATION_ERROR    :'AUTHENTICATION_ERROR',
    UNAUTHORIZED_ERROR      :'UNAUTHORIZED_ERROR',
    INTERNAL_SERVER_ERROR   :'INTERNAL_SERVER_ERROR',
    NO_DATA_FOUND           :'NO_DATA_FOUND',
    CONFLICT                : 'CONFLICT'
}